### ISSUE TITLE
DEBUG: crashing child

### ISSUE THREAD

**Issue by orlin** [petruisfan/node-supervisor#4]
I get `DEBUG: crashing child` all the time in the console.  Sometimes twice in a row.  On a rare occasion, supervisor exits with:

```
DEBUG: crashing child

node.js:522
  process._kill(pid, lazyConstants()[sig]);
          ^
Error: Bad argument.
  at EventEmitter.kill (node.js:522:13)
  at StatWatcher.crash (/Users/orlinbozhinov/.node_libraries/.npm/supervisor/0.1.0/package/lib/supervisor.js:132:11)
```

**Comment by klisly** [comment]
still has the problem, use nodemon is great
